### PR TITLE
Add pdd

### LINKED ISSUE #30: Add `pdd` to CI
Add `pdd` workflow to github workflows

### PR DESCRIPTION
**Pull request by c71n93**
Closes #30

---

## PR-Codex overview
This PR focuses on improving the PDD (Project Driven Development) workflow. 

### Detailed summary
- Added email error notifications for PDD violations.
- Added GitHub alert notifications for PDD violations.
- Updated PDD configuration file with new rules and exclusions.
- Added a GitHub Actions workflow for running PDD checks on push and pull request events.
- Refactored the `DGraphCondNode` class to gather arguments into a structure and refactor usages.

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by c71n93** [comment]
@Graur could you check this, please?

**Comment by c71n93** [comment]
@Graur could you check this, please?

**Comment by Graur** [comment]
@c71n93 I believe we can add a [configuration](https://github.com/objectionary/eo-hamcrest/blob/master/.pdd) file for `pdd`. WDYT?

**Comment by c71n93** [comment]
@Graur Sure, I'll try it

**Comment by c71n93** [comment]
@Graur done!

**Comment by Graur** [comment]
@c71n93 What about `.0pdd.yml`? 

As far as I know, we also need to invite [pdd](https://github.com/0pdd) bot to this repository. @yegor256 Can you help?

**Comment by c71n93** [comment]
@Graur added `.0pdd.yml`

**Review by Graur — APPROVED** [review]

**Comment by c71n93** [comment]
@yegor256 could you please check this one?

**Comment by yegor256** [comment]
@rultor merge

**Comment by Graur** [comment]
That's interesting. Looks like we need to change the architect here: https://github.com/objectionary/deog/blob/master/.rultor.yml#L2

**Comment by c71n93** [comment]
@yegor256 take a look, please

**Comment by yegor256** [comment]
@rultor merge

**Pull request merged**
